image: "node:18-alpine"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public

deploy-staging:
  stage: deploy
  script:
    - echo 'Staging deployment job'
  artifacts:
    paths:
      - public
  except:
    - master