stages:
  - install
  - build
  - deploy

install:
  stage: install
  script:
    - npm ci

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main

pages:
  stage: deploy
  script:
    - mv dist/ public/
  artifacts:
    paths:
      - public
  only:
    - main


